# Generated by Django 5.2.2 on 2025-06-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email",
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Укажите старну",
                        max_length=150,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Укажите город",
                        max_length=150,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Укажите улицу",
                        max_length=250,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "apt",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номер дома",
                        max_length=250,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название контрагента",
                        max_length=250,
                        verbose_name="Наименование контрагента",
                    ),
                ),
                (
                    "debt_to_supplier",
                    models.FloatField(
                        help_text="Введите задолженность перед поставщиком",
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанного поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.customers",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="выберите продукты",
                        related_name="products",
                        to="products.products",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "сontacts",
                    models.ManyToManyField(
                        help_text="выберите контакты",
                        related_name="сontacts",
                        to="partners.contacts",
                        verbose_name="Контакты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "ordering": ["name"],
            },
        ),
    ]
