# Generated by Django 5.2.2 on 2025-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="выберите продукты",
                null=True,
                related_name="products",
                to="products.products",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="сontacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="выберите контакты",
                null=True,
                related_name="сontacts",
                to="partners.contacts",
                verbose_name="Контакты",
            ),
        ),
    ]
