# Generated by Django 5.2.2 on 2025-06-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_customers_products_alter_customers_сontacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Введите email",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
