# Generated by Django 5.2.2 on 2025-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_alter_contacts_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="debt_to_supplier",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Введите задолженность перед поставщиком",
                null=True,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="сontacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="выберите контакты",
                null=True,
                to="partners.contacts",
                verbose_name="Контакты",
            ),
        ),
    ]
