# Generated by Django 5.2.2 on 2025-06-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_alter_customers_debt_to_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Укажите старну",
                max_length=150,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
