# Generated by Django 5.2.2 on 2025-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите название продукта",
                        max_length=250,
                        null=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        help_text="Укажите модель продукта",
                        max_length=150,
                        verbose_name="Модель продукта",
                    ),
                ),
                (
                    "release_at",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату выхода продукта",
                        null=True,
                        verbose_name="Дата выхода продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name", "release_at"],
            },
        ),
    ]
